### ISSUE TITLE
ImportError: No module named 'soql'

### ISSUE THREAD

**Issue by ghost** [plangrid/soql#4]
Good Day,

I'm trying to install this package in a python virtualenv 3.5. It installs but when I attempt to import the pacakge, I'm greeted with the following:

```
$ pip install soql
    Collecting soql
    Requirement already satisfied: python-dateutil in ./env/lib/python3.5/site-packages (from soql) (2.6.1)
    Requirement already satisfied: six in ./env/lib/python3.5/site-packages (from soql) (1.11.0)
    Installing collected packages: soql
    Successfully installed soql-1.0.1
```

```
>>import soql

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'soql'

```

Any advice?

**Comment by barakalon** [comment]
Ah, sorry about that. Looks like `find_packages` isn't working properly.
I have a fix, but I need to get permissions back in order (I don't work at PlanGrid anymore). Hang tight...

**Comment by barakalon** [comment]
@Ben-G Do you know if its possible to give me admin access to this repo? Or would you prefer I fork and open a PR?

**Comment by Ben-G** [comment]
@barakalon If whatever you need to do doesn't require admin rights, a PR would be great 🎉

**Comment by barakalon** [comment]
v1.0.2 is deployed, and appears to be working! Thanks @juliusiv and @Ben-G 
This issue can be resolved

**Comment by Ben-G** [comment]
👏 Thanks for the fix @barakalon!
