### ISSUE TITLE
How do I use logic in a 'where' clause?

### ISSUE THREAD

**Issue by crawforde** [plangrid/soql#8]
I'm currently trying to create a query with a string of where statements. One of these statements needs to have "or" logic in it. It's not clear from looking at the documentation how I would do that. I tried something like the following:
```
 select(SomeType) \
  .where(SomeObjectType.some_boolean == True or SomeType.some_str == "")
```
Looking at the resulting string reveals that the second part of the clause is completely ignored. What is the right way of doing this?

**Comment by barakalon** [comment]
Ah! You are right - this is missing from the documentation.

In the meantime, use the `or_` function: https://github.com/plangrid/soql/blob/master/soql/nodes.py#L268

That should look something like this:

```python
select(SomeType) \
  .where(or_(SomeObjectType.some_boolean == True, SomeType.some_str == ""))
```

**Comment by crawforde** [comment]
Awesome, thank you! That works for me. This great little package has a lot more useful tools than it advertises, including the `changes` function that is great for PUT operations.
